parameters:

services:
    ncrest.request_listener:
        class: Naukri\NcRestBundle\Listener\RequestListener
        tags:
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelRequest, priority:254}
    ncrest.ExceptionListener:
        class: Naukri\NcRestBundle\Listener\ApiExceptionListener
        arguments: ["@service_container"]
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority:254}
