api2:
    jd:
        class: JobDetailApi
        method: [GET:getJDDetails, POST:postEducation, PUT:putEducation, DELETE:deleteEducation]
        args:
          profile: [prId, 6]
          education : [edId, 4]
        order: true

    search:
        class: JobDetailApi
        method: [GET:getJDDetails, POST:postEducation, PUT:putEducation, DELETE:deleteEducation]
        args:
          user : [userId, s,]
          profile: [prId, 6]
          education : [edId, all   ]
        order: true
