imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    test: ~
    
    session:    
      cookie_httponly: true
      name: "JP_SESSION"
      handler_id:  jp.session.handler
      cookie_lifetime: 31536000

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            channels: ["!jp"]
            
        jp:
            type: fingers_crossed
            channels: ["jp"]
            handler: grouped
            action_level: info
            
        grouped:
            type: group
            members: [filestream, sqlhandle]   
            
        filestream:
            type: stream
            formatter: jp.log.formatter
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            
        sqlhandle:
            type:  service
            id: jp.sql.log.handler
            

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

parameters:
  custom.log.handler:
    level: debug
    email: "abc@gmail.com"
    
  BASE_STATIC_URL_S4: "http://test1.static.infoedge.com:8080/s/4"
  
  BASE_STATIC_URL_S1: "http://test1.static.infoedge.com:8080/s/1"
  
  BASE_STATIC_URL_S0: "http://test1.static.infoedge.com:8080/s/0"
  

  # external URLs
  REF_SHARE_URL: "http://test1.posting.infoedge.com/referral/vre"
  
  ASSET_MIN: ".min"
  
  zendmail:
      transport: smtp
      name: localhost
      host: localhost
      port: 25
      connection_class:
      user: 
      password: 
