imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    test: ~
    
    session:    
      cookie_httponly: true
      name: "JP_SESSION"
      handler_id:  jp.session.handler
      cookie_lifetime: 31536000

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            channels: ["!jp"]
            
        jp:
            type: fingers_crossed
            channels: ["jp"]
            handler: grouped
            action_level: info
            
        grouped:
            type: group
            members: [filestream, sqlhandle]   
            
        filestream:
            type: stream
            formatter: jp.log.formatter
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            
        sqlhandle:
            type:  service
            id: jp.sql.log.handler
            

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

parameters:
  custom.log.handler:
    level: debug
    email: "abc@gmail.com"
    
  BASE_STATIC_URL_IMG: "http://dev2.static.infoedge.com"
  
  BASE_STATIC_URL_CSS: "http://dev2.static.infoedge.com"
  
  BASE_STATIC_URL_JS: "http://dev2.static.infoedge.com"

  BASE_RSTATIC_URL_CSS: "http://dev2.rstatic.infoedge.com/trunk/web/css"


  BASE_STATIC_URL_S4: "http://dev2.static.infoedge.com/s/4"
  
  BASE_STATIC_URL_S1: "http://dev2.static.infoedge.com/s/1"
  
  BASE_STATIC_URL_S0: "http://dev2.static.infoedge.com/s/0"
  
  AC_IMG_PATH: "%BASE_STATIC_URL_S4%/113_v5.0.0/src/i"    
  AC_CSS_PATH: "%BASE_STATIC_URL_S4%/113_v5.0.0/src/c"    
  AC_JS_PATH: "%BASE_STATIC_URL_S4%/113_v5.0.0/src/j"

  NC2_IMG_PATH: "%BASE_STATIC_URL_S1%/2/i"    
  NC2_CSS_PATH: "%BASE_STATIC_URL_S1%/2/c"    
  NC2_JS_PATH: "%BASE_STATIC_URL_S1%/2/j"
    
  NC0_IMG_PATH: "%BASE_STATIC_URL_S0%/0/src/i"    
  NC0_CSS_PATH: "%BASE_STATIC_URL_S0%/0/src/c"    
  NC0_JS_PATH: "%BASE_STATIC_URL_S0%/0/src/j"
  
  

  # external URLs
  REF_SHARE_URL: "http://dev1.infoedge.com:8000/jobpostingMayank/index.php/referral/vre"
  
  ASSET_MIN: ""
  
  zendmail:
      transport: smtp
      name: localhost
      host: localhost
      port: 25
      connection_class:
      user: 
      password:
