imports:
    - { resource: config_base_cluster.yml }
#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:  stream
            path:  "/apps/jp/current/app/logs/prod.handler.log"
            level: error
            channels: ["!jp"]

        jp:
            type: fingers_crossed
            channels: ["jp"]
            handler: grouped
            action_level: info

        grouped:
            type: group
            members: [filestream, sqlhandle]

        filestream:
            type: stream
            formatter: jp.log.formatter
            path:  "/apps/jp/current/app/logs/prod.file.log"
            level: info

        sqlhandle:
            type:  service
            id: jp.sql.log.handler

parameters:
  CLUSTER_URL: '{{CLUSTER_URL}}'
  custom.log.handler:
            level: error
            email: "rohit.sharma1@naukri.com"


  BASE_STATIC_URL_IMG: "https://static.%CLUSTER_URL%"
  BASE_STATIC_URL_CSS: "https://static.%CLUSTER_URL%"
  BASE_STATIC_URL_JS: "https://static.%CLUSTER_URL%"

  BASE_RSTATIC_URL_CSS: "http://test2.static.infoedge.com/rstatic/css"


  # external URLs
  REF_SHARE_URL: "https://posting.%CLUSTER_URL%/referral/vre"

  ASSET_MIN: ".min"

  zendmail:
      transport: smtp
      name: mail-service
      host: mail-service
      port: 25
      connection_class:
      user:
      password:
