imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            channels: ["!jp"]
            
        jp:
            type: fingers_crossed
            channels: ["jp"]
            handler: grouped
            action_level: info
            
        grouped:
            type: group
            members: [filestream, sqlhandle]   
            
        filestream:
            type: stream
            formatter: jp.log.formatter
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            
        sqlhandle:
            type:  service
            id: jp.sql.log.handler    
