jms_security_extra: 
    secure_all_services: false
    expressions: false
        
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: [ROLE_MANAGER, ROLE_RECRUITER, ROLE_MANAGE_WORKFLOW, ROLE_MANAGE_RECRUITERS, ROLE_MANAGE_SETTINGS, ROLE_DOWNLOAD]

    providers:
        jpsso:
            id: jpsso.security.user.provider

    firewalls:
        jp_open_api:
            pattern: ^/resource/openApi
            security: false
        jp_ops_interface:
            pattern: ^/operations
            security: false
        jp_insta:
            pattern: ^/hiring/instajob
            security: false
        jp_sso:
            pattern: ^/
            jpsso: true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /logout
                target: /
