jobposting:
    #First step will be job post, whose jobId will be saved as reference in next steps
    #N-Naukri, R-Referral, C-CareerSite, I-InternalJob, E-ExternalBoards
    Naukri:
        postingWorkFlow:
          - applyPaf
          - applyNfl
          - notifyPublisher 
    CareerSite:
        postingWorkFlow:
          - applyPaf
          - notifyPublisher
    ExternalBoards: true
        
    #Last step is publishing job to RMS publisher queue
