parameters:
     jpsso.security.authentication.listener.class: Naukri\JobPostingGatewayBundle\Util\Auth\JPSSOAuthListener
#     utbundle.smarty.custom.render.class: Naukri\UtilityBundle\UtilSmartyExtension\CustomRenderExtension

services:
    jpsso.security.authentication.listener:
        class: %jpsso.security.authentication.listener.class%
        arguments: ["@security.context", "@security.authentication.manager", "@templating"]
    jp.log.formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%channel%%.%%level_name%%]: [%%extra.token%%] [%%extra.class%%]:[%%extra.function%%] in line %%extra.line%%: %%message%% %%context%%\n"
