<?php

namespace Naukri\UtilityBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class NaukriExceptionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Naukri\UtilityBundle\Controller\NaukriExceptionController();
        return $instance;
    }
}
