<?php

namespace Naukri\JobPostingGatewayBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class JobReportsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Naukri\JobPostingGatewayBundle\Controller\JobReportsController();
        $refProperty = new \ReflectionProperty('Naukri\\JobPostingGatewayBundle\\Controller\\BaseController', 'authenticationUtil');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('jp.auth.util', 1));
        $instance->jobReportsService = $container->get('job.report.service', 1);
        return $instance;
    }
}
